### ISSUE TITLE
Passing in custom renderers?

### ISSUE THREAD

**Issue by montezume** [DanWebb/jdown#1]
Would you be open to PRs?

I recently made a site using react static, but I needed to be able to render anchor tags with "_blank". How about having `jdown` accept parameters to pass down to metalsmith to allow for custom markdown renderers?

**Comment by DanWebb** [comment]
Yes! This is something I had intended to add and think opening a way to pass options down to metalsmith would be the way to go rather than inventing anything new.

**Comment by DanWebb** [comment]
Closing in favour of #3 will get back to you on the PR once I've had a chance to properly review 😀

**Comment by montezume** [comment]
Sure thing 👍. Could also add some jest unit testing, feels weird to make a PR without any unit tests 😬
