### ISSUE TITLE
Vulnerabilities reported on installation

### ISSUE THREAD

**Issue by barnsey-tran** [DanWebb/jdown#10]
Hi,
Can you update the version of some dependencies? Npm v 6.2 reports 8 vulnerabilities and it kinda makes me nervous.

**Comment by DanWebb** [comment]
Hi @barnsey-tran I've updated what I can in release 0.6.5 but all the moderate level vulnerability warnings are coming from the imagemin package, there are already issues reported for it https://github.com/imagemin/imagemin-gifsicle/issues/22

You can find more info on the vuln here https://snyk.io/vuln/npm:tunnel-agent:20170305 as it says `This is vulnerable only for Node <=4` so I'd guess you're on a later version of node and don't need to worry about it.

I'll keep an eye out on the issue anyway and update jdown dependencies once it get's fixed.
