### ISSUE TITLE
Return file names for items in collections

### ISSUE THREAD

**Issue by benedfit** [DanWebb/jdown#13]
Would it be possible to return the file name of any items that are found in collections as an additional property on each item?

e.g. The "work" collection below would become:

```
"work": [{ "name": "work-post-one", "contents" "..."}, { "name": "work-post-two", "contents" "..."}]
```

![image](https://user-images.githubusercontent.com/580859/49019524-082eda00-f186-11e8-9da9-c1e2ba3b4dd3.png)

I'm currently achieving this by having an additional field that mirrors the file name that I'm using to form URLs in the app

**Comment by DanWebb** [comment]
Hi @benedfit potentially, I'm not totally convinced it would be a common enough use case though keeping in mind we want to keep the output as uncluttered as possible.

I would instead handle this problem by adding a "name", "slug" or "handle" property into the frontmatter. This is pretty common to open this up as a separate field in CMS's for admins to be able to modify URL's and other SEO fields for the page so having it in frontmatter also makes it more accessible if that's needed later.

Please let me know if for some reason adding the name you suggest to frontmatter wouldn't work for your use case and I may reconsider.

**Comment by benedfit** [comment]
I totally get your stand point. My particular use case means was a selfish one. Because I’m already create files with the same name as what I would want in a “slug” field, I was hoping to prevent some duplication. Thanks for considering it

**Comment by DanWebb** [comment]
OK, so sounds like we both agree it shouldn't be included by default. I can see why it could be helpful though so after thinking about it I will add it as an option as there may be other file-based info people want to expose as properties, like the files "created at" date. If the option to include it is enabled it could be stored in a `fileInfo` object to avoid clashing with properties in frontmatter.
