### ISSUE TITLE
Bug: jdown module not found

### ISSUE THREAD

**Issue by IOIO72** [DanWebb/jdown#14]
I just updated my project from v0.6.6 to v1.0.0 and I'm getting a missing module error.

I'm importing jdown by using:
`import jdown from 'jdown';`

Do I need to import it another way?

I'm using the module inside my `static.config.js` for my React Static site.

**Comment by DanWebb** [comment]
Hey @IOIO72 thanks for reporting and sorry about the error.

If you can update to v1.0.1 you will not experience the problem again.
