### ISSUE TITLE
ENOENT: No such file or directory

### ISSUE THREAD

**Issue by dnndev** [DanWebb/jdown#2]
Thanks for jdown. Using it in `react-static` is wonderful. However, I've run into a problem while trying to create a production build.

ENOENT: no such file or directory, scandir 'C:\Program Files (x86)\Jenkins\workspace\Chicago_Astronomical_Society_Website\node_modules\jdown\content'

I can do a production build locally on my Mac with no problems using `yarn build`. However, when I try to build from within Jenkins, I run into the above error. The error message _seems_ to indicate it's looking for the `content` directory within the jdown folder. I'm not sure where to look to debug further.

**Comment by dnndev** [comment]
Here's the relevant (I believe) portion of my `static.config.js` file:

```javascript
export default {
  getSiteData: () => ({
    title: 'My Website',
  }),
  getRoutes: async () => {
    const { posts  } = await jdown('content')
    return [
```
If I change the jdown call to `jdown('/content')` then the error message indicates it's scanning `C:\content`; If I change it to `jdown('../content')` then it scans `c:\Program Files\...\node_modules\content`; 

Finally, if I change it to `jdown('../../content')` the I get a different error: *Cannot read property 'map' of undefined*

**Comment by DanWebb** [comment]
Hi @dnndev thanks for your feedback! I've applied a fix for the issue this morning, could you try updating to version 0.2.0 and let me know if you still face any issues.

**Comment by dnndev** [comment]
Hi Dan,

I believe that resolved the path issue. However, it may have exposed something else. I'll open a different issue for that. :)
