### ISSUE TITLE
collection ordering

### ISSUE THREAD

**Issue by j4p3** [DanWebb/jdown#5]
Hello. Great library! I'm thinking about post ordering. At the moment, It looks like it relies on Metalsmith's default order. I'd like to create an option here for ordering output by date (Metalsmith seems to support this via their 'Archive' plugin).

Thoughts? Is this something you would support here?

**Comment by DanWebb** [comment]
Hey @j4p3, thanks! Jdown outputs JSON so if you added a date to the markdown files in frontmatter you could order content based on the dates returned in the JSON with [Array.sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort).

Hopefully that makes sense but let me know if not and I could provide some examples. Eventually jdown could open up a way to pass down metalsmith plugins but that's not a feature just yet.

**Comment by j4p3** [comment]
Hey, thanks for the quick reply. Yes, that's what I've been looking at doing - it's not as if it's a performance hit to just sort the array on build. I do a similar draft/public operation in the config file for a react-static site.
