### ISSUE TITLE
How to Disable Contents Markdown Conversion?

### ISSUE THREAD

**Issue by FullstackJack** [DanWebb/jdown#6]
Hi, I would like to use react-markdown to render the `contents` on a page in order to avoid React's `dangerouslySetInnerHTML`. How would I disable the conversion of `contents`? I would still like to get the front matter and contents separate for building a react-static blog.

**Comment by FullstackJack** [comment]
Looks like I'll just have to pass it back through an HTML to Markdown converter [turndown](https://github.com/domchristie/turndown) and then back through Markdown to React converter [react-markdown](https://github.com/rexxars/react-markdown). Insanity! :trollface:

**Comment by DanWebb** [comment]
Hey @FullstackJack thanks for raising this issue. If you only would like to avoid using `dangerouslySetInnerHTML` you could look at using https://github.com/pveyes/htmr or similar. An example of doing so can be found in the React static markdown example source code https://github.com/nozzle/react-static/blob/master/examples/markdown/src/containers/Home.js

**Comment by FullstackJack** [comment]
Nevermind. I can just use react-markdown's `escapeHtml={false}` prop.

https://github.com/rexxars/react-markdown#options

**Comment by DanWebb** [comment]
Hey @FullstackJack I had a think about this and have implemented some updates in the latest version of jdown which adds a parseMd option.

To disable the markdown parsing you can use this option like so:
```
jdown('path/to/markdown/content', {parseMd: false}).then(content => console.log(content));
```

Full example here https://github.com/DanWebb/jdown/blob/master/example/without-md-parsing.js
