### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by bkniffler** [DanWebb/jdown#7]
Hey, if I refer an image `![](./photo.jpg)` from markdown and add the image into the folder, jdown tries to parse the image (I think). It would be good to exclude extensions or to only include .md. Also it would be great to find a solution to include those images into the public dist folder of react-static, but I
'm not sure this is the right place to discuss about this.

**Comment by bkniffler** [comment]
Oh, I see that this is an issue with metalsmith.

**Comment by DanWebb** [comment]
Hey @bkniffler, if you're using react-static you should have a /public folder at the root of your site which contains static assets.

These will get added to the dist folder automatically. Say you placed your photo.jpg asset in the public folder then you would be able to reference it in your markdown like: `![](/photo.jpg)`. You can also add subfolders in the /public dir to organise the content in it and then be able to reference photo like `![](/subfolder/photo.jpg)`.

Or is the issue that you already know this and wanted to keep the assets in the folders next to the markdown anyway out of preference?

**Comment by bkniffler** [comment]
Yes, I'd love to have a content folder that contains all source files (markdown and images). Then I'd like to somehow transform the files (compression and adding cache keys to image filenames just like its currently done when they sit in public folder). 

I know this wouldn't be a problem if I required those inside my react elements since Webpack does all of this (if I add a .md rule of course), but this would render the whole CMS part useless. And I know I can use the public folder, but then I'd have 2 separate source folders, which would be more difficult to reason for the content creators. Currently I've no idea how to do it. 

btw. With Gatsby (which I evaluated first, but I prefer react-static due to not relying on graphql) it worked really well, but I guess that it works fundamentally different to react-static.

**Comment by DanWebb** [comment]
Thanks for the extra input. This would be a nice feature, I can't promise anything but I'll re-open and investigate/run some tests to see if it could be handled somehow. I'm all ears so if you have any ideas too!

In the meantime, I know not getting your own way in terms of how you want to organise things can be really painful to accept and it's part of why I created jdown in the first place, but you could use the public folder for now.

**Comment by bkniffler** [comment]
Thanks for considering this a good idea. One big issue of public folder is that it gets copied to dist folder without any optimizations. This gets really annoying if we start using something like tiff files. If we could have .md files converted by webpack without importing them inside the components, but in static.config.js, that would be really cool.

**Comment by DanWebb** [comment]
Hey @bkniffler I've been working on this feature, you can see progress so far in the images branch of this repo https://github.com/DanWebb/jdown/tree/images

I've still got some test cases to write/run but it's nearly there. It'd be a massive help if you could have a quick review and let me know your thoughts and if it looks like it suits what you were looking for.

Essentially, `images/` sub-directories can be added in any of the contents folders (take a look at /example/content) then the images can be referenced from the md files using `./images/image.png`. It's possible to set an output directory as well as a base path and some minification in the options like:
```
jdown('example/content', {
  asset: {
    output: './your/static/file/directory',
    path: '/public' // images src will end up as path + imagename.ext
    png: {quality: '65-80'} // passed to imagemin
  }
})
```
The image files get run through [imagemin](https://github.com/imagemin/imagemin) and have an `mtime` (last modified time) timestamp appended to their file names for cache busting.

It's currently possible to place an images folder in the top contents directory and then reference the images from that folder in subfolder md files like:
```
- images/
  | - image.png
- collections/
  | - blog/
  |   | - post.md <-- can use ./images/image.png
```
This wasn't intended but I don't mind it, as some people might just want a single image folder. However, I think if an images folder was placed inside collections/blog folder that contained a file called image.png it should overwrite it. 

This is backwards compatible so the images directories and asset options are completely optional.

**Comment by cwaring** [comment]
@DanWebb thank you for working on this feature! I was trying to do exactly the same thing with jdown and react-static recently, which lead me to this issue. I'll test this out shortly and report back too.

**Comment by DanWebb** [comment]
@cwaring @bkniffler Just pushed some further updates to the images branch for this:
- Added subfolder prefixes to output filenames, so `/content/blog/assets/asset.png` will be output as `blog-asset-{mtime}.png`. This solves the issue I mentioned in my last comment with files and duplicate names in subfolders whilst still allowing people to use a single asset folder in the root contents dir instead of multiple asset folders if they want to.
- Renamed /images folders to /assets just to make the naming more consistent.
- Added tests for the asset transforms.

I think it just needs some more tests with varying file extensions (currently tested with .png, .jpg, .svg) and some docs written up before the features released. If you do get a minute any feedback would be awesome!

**Comment by bkniffler** [comment]
After a quick review, this seems to work really nicely. I will not be able to review it further for now since I'm finishing another project first, but react-static + jdown is going to be the foundation of the next website project soon. Great work @DanWebb and thanks for the quick updates! 

Maybe you could also allow to have completely random/hashed names for assets or use a string pattern for renaming assets like '{name}-{mtime}' / '{hash}' or so. When people drop stupidly named images into the markdown editor like "sword-art-cool-karton-wallpaper-desktops-background-wallpapers.jpg.png" (an actual file in my download folder :P), I'd rather have it completely renamed.

**Comment by DanWebb** [comment]
Thanks for the feedback @bkniffler!

**Comment by DanWebb** [comment]
I'm going to close this issue as the latest version of jdown 0.6.4 contains the feature 🚀

Check the [assets section of the readme](https://github.com/DanWebb/jdown#placing-assets-inside-the-content-directory) for more details.
