### ISSUE TITLE
Imges 

### ISSUE THREAD

**Issue by bernatfortet** [DanWebb/jdown#9]
hi @DanWebb jdown is awesome! Good stuff 👍 

I was reading #7 and the latest implementation of the assets process. 
I'm having trouble with the follwing structure

```
|- contents
| |- collections
| | |- projects
| | | |- project-1
| | | | |- body.md <- 🚨 ./assets/my-asset.png is not appending the cache numbers 
| | | | |- assets
| | | | | |- my-asset.png
```

I also tried
```
|- contents
| |- projects
| | |- project-1
| | | |- body.md <- 🚨 ./assets/my-asset.png is not appending the cache numbers 
| | | |- assets
| | | | |- my-asset.png
```
Any though on how to make it work?

**Comment by grzechz** [comment]
Hi @bernatfortet,
Do you use the newest version of jdown? I had similar issue when I was using some old version.

**Comment by bernatfortet** [comment]
I thought so. 
I eventually used another system.
Thanks

**Comment by DanWebb** [comment]
Hey @bernatfortet Thank you 😊 and sorry it took me a while to get to this one for you, glad it sounds like you found a solution though.

I think the version issue @GrzegorzAdamZadora mentioned is most likely it. I did create a test case matching your folder structure but the only way I could reproduce was if the asset in markdown didn't have the same name as the actual asset I was attempting to reference. I'll close the issue for now but please do let me know if you see any similar issue again, I'll try to reply back in better time.

Purely out of interest - what was the other system you ended up using?

**Comment by bernatfortet** [comment]
Thanks @DanWebb, I ended up using Figma as a CMS! It's a very interesting approach. For now I'm only using it for my mother's website: http://ligiaunanue.com/
